### ISSUE TITLE
Create MySQL Database

### ISSUE THREAD

**Issue by Miserlou** [Miserlou/zappa-django-utils#1]
We can create a PG DB, we should throw a bone to the MySQL/Aurora people too..

**Comment by djstein** [comment]
so it appears that this file exists: https://github.com/Miserlou/zappa-django-utils/blob/master/zappa_django_utils/management/commands/create_mysql_db.py

I however cannot test that it is working since the command did not make it into 0.4.0 version of https://pypi.org/project/zappa-django-utils/

could someone please build and push a new version to PyPi?
@Miserlou @jnoortheen @AlmogCohen

**Comment by khamaileon** [comment]
Is there an upcoming release?

**Comment by Vadorequest** [comment]
I strongly suggest to replace the line
>     cur.execute(f'ALTER DATABASE `{dbname}` CHARACTER SET utf8')

by
>     cur.execute(f'ALTER DATABASE `{dbname}` CHARACTER SET utf8mb4')

See https://medium.com/@adamhooper/in-mysql-never-use-utf8-use-utf8mb4-11761243e434
